### ISSUE TITLE
希望hangout能够有类似logstash的urldecode功能和KV插件中的include_keys功能

### ISSUE THREAD

**Issue by xiagujinqiao** [childe/hangout#1]
hello，childe，公司线上部分日志比较乱，实际使用过程中，发现还需要类似logstash 的urldecode插件和kv插件中的include_keys功能。如果方便的话，希望能够有这个新功能，谢谢你。
logstash：
	urldecode {
                #all_fields => true
                field => ["url_args"]
        }

KV:
        kv {
            prefix => "url_"
            source => "url_args"
            field_split => "&"
            include_keys => [ 'appv','net','osn','osv' ]
    	}

**Comment by childe** [comment]
add the features in 39e649 and be7ad7
