### ISSUE TITLE
hangout_log

### ISSUE THREAD

**Issue by Gongruixiao** [childe/hangout#100]

**Comment by Gongruixiao** [comment]
hangout版本0.3.0

想要hangout运行时，指定日志文件输出。修改了log4j2.xml文件，没有生效。请问运行时如何指定具体的日志文件

**Comment by childe** [comment]
```
% cat log4j2.xml                                                                                                                                                                                                              ✭
<?xml version="1.0" encoding="UTF-8"?>
<Configuration status="error">
  <Appenders>
    <Console name="Console" target="SYSTEM_OUT">
      <PatternLayout pattern="%d [%t] %-5level %logger{36} - %msg%n"/>
    </Console>
    <File name="File1" fileName="output.log" bufferedIO="false">
      <PatternLayout pattern="%d [%t] %-5level %logger{36} - %msg%n"/>
    </File>
  </Appenders>
  <Loggers>
    <Root level="${env:HO_LOG_LEVEL}">
      <AppenderRef ref="File1"/>
    </Root>
  </Loggers>
</Configuration
```

我这么设置的, 试了一下可以的.

**Comment by Gongruixiao** [comment]
我是自己百度查的log4j资料改的，发现并没有生成hangout.log文件
<?xml version="1.0" encoding="UTF-8"?>
<Configuration status="${env:HO_LOG_LEVEL}">
  <Appenders>
    <Console name="Console" target="SYSTEM_OUT">
      <PatternLayout pattern="%d [%t] %-5level %logger{36} - %msg%n"/>
    </Console>
    <FileAppender name="File" fileName="hangout.log">
      <PatternLayout pattern="%d [%t] %-5level %logger{36} - %msg%n"/>
    </FileAppender>
  </Appenders>

  <Loggers>
    <Root level="${env:HO_LOG_LEVEL}">
      <AppenderRef ref="File"/>
      <AppenderRef ref="Console"/>
    </Root>
    <Logger level="${env:HO_LOG_LEVEL}" additivity="true">
      <AppenderRef ref="File"/>
      <AppenderRef ref="Console"/>
    </Logger>
  </Loggers>
</Configuration>

**Comment by Gongruixiao** [comment]
你好，我参照你的配置文件进行了设置，通过启动命令./bin/hangout -f ***.yml 也没有观察到有日志文件output.log文件的生成，请问是还需要修改其他地方吗 @childe

**Comment by childe** [comment]
@Gongruixiao 你看一下hangout目录下的VERSION文件内容, 确认一下commit号是多少.

或者自己make一下最新的?
```
git clone git@github.com:childe/hangout.git 
cd hangout
make
```
