### ISSUE TITLE
hangout elasticsearch http 接口支持url编码的用户名和密码

### ISSUE THREAD

**Issue by YDHui** [childe/hangout#101]
@childe 我想问下elasticsearchHTTP的output能否支持url编码的用户名和密码，比如说
hosts:
  - elastic:123qwe@192.168.11.11:9200
这种形式，集群版本是5.2.0

**Comment by childe** [comment]
我还没有测试过这样行不行, 我争取今天加上username password的功能啊啊啊啊

**Comment by childe** [comment]
添加了这个功能 7496d978f661da084e7a09efa1011edaee31c93c
配置参考  https://github.com/childe/hangout/blob/master/conf/testeshttpoutput.yml

git clone 之后 make 一下吧~

**Comment by YDHui** [comment]
OK，过两天我测试下，这两天比较忙

**Comment by YDHui** [comment]
@childe 测试可行，感谢
