### ISSUE TITLE
make后./bin/hangout不可执行

### ISSUE THREAD

**Issue by RickyHuo** [childe/hangout#102]
git拉取的最新mater分支，IDEA中运行（WINDOW）
> clean package -DskipTests

打包后放到工作环境，解压运行
> ./bin/hangout -f ...

不可执行。

观察`./bin/hangout`属性为
> -rw-r--r-- 1 root root 352 Sep 25 18:19 hangout

release中对应文件属性
> -rwxr-xr-x 1 root root 288 Jun 30 11:26 hangout

是不是我IDEA有哪里没有配置？

**Comment by childe** [comment]
@RickyHuo 执行release里面的bin/hangout.

**Comment by RickyHuo** [comment]
@childe  上面说的release是你提供的编译好的ZIP文件。

重新看了遍Makefile， 运行chmod +x 后还是不能执行，报错
```
[root@10 hangout]# ./bin/hangout -f conf/example.yml 
bash: ./bin/hangout: /bin/sh^M: bad interpreter: No such file or directory
```

查阅了相关文档[bad interpreter](http://blog.csdn.net/stpeace/article/details/45604015)已经解决了问题， 感谢。
