### ISSUE TITLE
Filters Date支持不同时区和增加target选项

### ISSUE THREAD

**Issue by YDHui** [childe/hangout#106]
@childe 在使用filter date模块时，发现date只是做格式化，并不能像logstash date模块那样能够将字符串转化为时间类型的选项，因此在写到ES的时候会报错，另外，能否添加时区的选项，能够自由选择转化的时区，谢谢
我的配置如下：
![image](https://user-images.githubusercontent.com/12887714/34252260-d928d314-e67d-11e7-801b-7f10f06addcb.png)

**Comment by childe** [comment]
timezone: "Asia/Shanghai"

应该是指这个?

**Comment by YDHui** [comment]
![image](https://user-images.githubusercontent.com/12887714/34282891-c81b5804-e703-11e7-8e23-4969d1897e8a.png)
写入es的时候，因为app_time这个字段是date类型，所以一直报这个错
我打到标准输出是这样子的
![image](https://user-images.githubusercontent.com/12887714/34283186-6a329110-e705-11e7-90c3-dcf5aa3e4f32.png)

**Comment by childe** [comment]
报错的截图, 看起来是ES的日志, 是说有个字段设置了date类型, 但你的数据不是ES默认支持的日期格式.
你首先要确认是哪个字段出的错, 这个在ES日志中应该也有. 然后你可以:
1. hangout里面用Date filter把它转换成标准格式.
2. ES的mapping里面自定义date format. https://www.elastic.co/guide/en/elasticsearch/reference/5.3/mapping-date-format.html

**Comment by YDHui** [comment]
嗯，我想问下Date filter能否将北京时间转换为其他时区的时间，谢了

**Comment by childe** [comment]
其实在ES中存的Date并没有时区的概念, 是unix timestamp, 一个Long型. 
date filter也只能指定src字段里面的时间是什么时区, 而不可能"转成其他时区的时间", 其实没有这个概念, 全是unix timestamp

**Comment by YDHui** [comment]
因为我之前用logstash的时候，使用logstash的date功能可以实现如下图的效果
![image](https://user-images.githubusercontent.com/12887714/34292797-2f1fe0fe-e73d-11e7-812f-480e3d4e5630.png)
因为我们要在kibana做展示，kibana默认会加8个小时，所以我们就转成了UTC时间，但是由于数据量太大，导致logstash资源消耗太猛，所以想看看hangout能否实现相同的功能，
我的logstash配置如下：
![image](https://user-images.githubusercontent.com/12887714/34292860-6f06f874-e73d-11e7-9d35-ab404a84a06f.png)

**Comment by YDHui** [comment]
@childe 问题解决了！
![image](https://user-images.githubusercontent.com/12887714/34293628-56188d0c-e740-11e7-845e-5f7f4baedd5d.png)
date里面加上时区信息，
ES指定format，"format":"YYYY-MM-dd'T'HH:mm:ss.SSSZ",就解决了!
多谢
