### ISSUE TITLE
hangout支持调用第三方接口和写入mysql吗？

### ISSUE THREAD

**Issue by mrzhangxing** [childe/hangout#108]
比如取出消息的某一个字段的value，然后去GET/POST一个接口得到返回值，重组数据然后在写入mysql

**Comment by childe** [comment]
目前这两个都不支持.

Http请求到是可以写一个filter, 但量大的情况下, 这个处理速度就太慢了吧. 你确定可行吗?

Mysql可以写output, 但实在是不熟悉数据库这套.

**Comment by mrzhangxing** [comment]
目前有个需求量级不是很大，但是需要额外重组消息，其实有的GET/POST请求，不需要mysql支持也行；以现状的版本该怎么写filter呢

**Comment by childe** [comment]
@mrzhangxing 如果可能有一个映射表, 我一般是用transport这个filter, 可以定期更新这个映射表, 把他放在一个远端web服务上面.
如果实在没有这样的映射表, 那我就写一个HTTP Filter吧 :(

映射表就是普通的Yml文件, 像下面这样

```
zhangsan: 10
lisi: 20
```

**Comment by mrzhangxing** [comment]
恩，感谢支持
