### ISSUE TITLE
支持按指定符切割消息, 并生成相应的字段属性

### ISSUE THREAD

**Issue by modeyang** [childe/hangout#11]
如题需求，类似于logstash利用ruby方法 split方法？

**Comment by childe** [comment]
不是很确定你什么意思?
是不是这样: 一个字符串 abc-123-xyz, 你想生成三个字段, {a:abc, b:123, c:xyz} ?
如果是这样的话, 用grok可以.

**Comment by modeyang** [comment]
就是这种意思，但是有时候字符串太长，而且分隔符比较复杂时，用grok就太繁琐，利用split方法可以简化生成字段的过程。

**Comment by childe** [comment]
我个人觉得用grok挺简单的, 比如说 ^%{DATA:a}\|%{DATA:b}\|%{DATA:c}\|%{DATA:d}\|%{DATA:e}\|%{DATA:f}$ , 复制粘贴很快就做好了. 所以我就觉得没必要再单独弄一个split了 :)

**Comment by modeyang** [comment]
好的， 我试试看下。谢谢。
