### ISSUE TITLE
请问，每收集一个日志文件，都要单独起一个hangout进程么？

### ISSUE THREAD

**Issue by shuxiaxia** [childe/hangout#111]
请问，每收集一个日志文件，都要单独起一个hangout进程么？
另外 HO_HEAP_SIZE="${HO_HEAP_SIZE:=2000m}" 这个值一般根据什么指标来调整，本人不太懂java

**Comment by childe** [comment]
收集日志文件, 建议使用es官方的filebeat.  hangout不能收集文件中的日志.
你可以根据数据量以及每一条的大小, 以及写ES的bulk批次大写等决定.
