### ISSUE TITLE
es6.2版本需要hangout修改什么才能支持呢？

### ISSUE THREAD

**Issue by mrzhangxing** [childe/hangout#114]
使用原来ES5对应的hangout版本，直接写入ES6中，报错：
```
bulk got exception: None of the configured nodes are available: 
```
该怎么处理呢

**Comment by gnuhpc** [comment]
@mrzhangxing 鼓励你写个pr啊，没几行代码

**Comment by childe** [comment]
@mrzhangxing 我自个加了 https://github.com/childe/hangout/releases/tag/es-6.2.2

**Comment by mrzhangxing** [comment]
@gnuhpc 感谢指导
@childe 辛苦
