### ISSUE TITLE
grok不支持中括号

### ISSUE THREAD

**Issue by Sartner** [childe/hangout#12]
grok: %{NUMBER:[prefix][field]}

会报grokfailed

**Comment by childe** [comment]
字段名叫 [prefix][field]?? 你是什么需求, 感觉不是这么用的.

**Comment by Sartner** [comment]
logstash 写ES如果有嵌套就要用中括号
写到ES里会变成prefix.field
ES不支持直接写“.”

**Comment by childe** [comment]
但据我了解, 这也不是grok中能用的语法.  grok出来就是一层的key:value这样的字典吧. 如果你一定需要多层的json(虽然我觉得好像没这个必要), 只能配合别的filter使用

**Comment by octowhale** [comment]
不是不支持，可以使用转义符支持。但是转义符需要预先转义。
有点拗口，举个例子
要实现  `[xxxxx]`  必须 `\\[xxxxx\\]`

**Comment by childe** [comment]
现在ES支持直接用“prefix.field”了, 完全等于 [prefix][field]
