### ISSUE TITLE
hangout 清洗日志到clickhouse CPU过高问题

### ISSUE THREAD

**Issue by tianjinsong** [childe/hangout#128]
hangout 清洗日志到clickhouse CPU使用率到达300%以上，怎么解决

**Comment by RickyHuo** [comment]
@tianjinsong hangout-output-clickhouse 的问题麻烦移步到 [hangout-output-clickhouse](https://github.com/RickyHuo/hangout-output-clickhouse)

**Comment by tianjinsong** [comment]
这个应该跟hangout-output-clickhouse没有关系吧

**Comment by RickyHuo** [comment]
可以试着不写ClickHouse，看看CPU使用率，如果也是300%以上，那就和写ClickHouse没关系

**Comment by tianjinsong** [comment]
我只打到控制台CPU使用率也是300%以上

**Comment by childe** [comment]
@tianjinsong 配置文件看一下?

**Comment by tianjinsong** [comment]
inputs:
    - NewKafka:
        topic:
           *********: 4
        codec: plain
        consumer_settings:
            bootstrap.servers: *********
            value.deserializer: org.apache.kafka.common.serialization.StringDeserializer
            key.deserializer: org.apache.kafka.common.serialization.StringDeserializer
            group.id: hangout

filters:
    - Filters:
        if:
          - '<#if message??&&message?contains("*********")>true</#if>'
        filters:
            - Grok:
                match:
                  - '^(?<dt>.*)\s+(?<time>\d\d:\d\d:\d\d),\d+.*logTheme=(?<logTheme>(.*)),host=(?<host>(.*)),ip=(?<gip>(.*)),request=(?<request>(.*)),response=(?<response>(.*)),time=(?<duration>\d+)$'
                remove_fields: ['message','@timestamp']
            - Json:
                field: request
                remove_fields: ['request','ip']
                tag_on_failure: ''
            - Json:
                field: response
                remove_fields: ['response','data']
                tag_on_failure: ''
            - Add:
                fields:
                     'logTime': ${dt} ${time}
            - Convert:
                fields:
                    duration:
                      to: integer
            - Rename:
                fields:
                  gip: ip
            - GeoIP2:
                source: ip
                target: geoip
                database: '/data/GeoLite2-City_20180605/GeoLite2-City.mmdb'
                country_code: false
                country_name: true
                country_isocode: false
                subdivision_name: true
                city_name: true
                latitude: true
                longitude: true
                location: false
                tag_on_failure: ''
            - Remove:
                fields:
                  - geoip
                  - time

outputs:
#    - Stdout:
#        if:
#          - '<#if logTheme??&&logTheme=="1003">true</#if>'
    - com.sina.bip.hangout.outputs.Clickhouse:
        if:
          - '<#if logTheme??&&logTheme=="1003">true</#if>'
        host: *********
        format: TabSeparated
        username: *********
        password: *********
        database: *********
        table: *********
        fields: *********
        bulk_size: 1000
    - com.sina.bip.hangout.outputs.Clickhouse:
        if:
          - '<#if logTheme??&&logTheme=="1004">true</#if>'
        host: *********
        format: TabSeparated
        username: *********
        password: *********
        database: *********
        table: *********
        fields: *********
        bulk_size: 1000
    - com.sina.bip.hangout.outputs.Clickhouse:
        if:
          - '<#if logTheme??&&logTheme=="1007">true</#if>'
        host: *********
        format: TabSeparated
        username: *********
        password: *********
        database: *********
        table: *********
        fields: *********
        bulk_size: 1000

**Comment by childe** [comment]
@tianjinsong 在做IO的时候, 比如说读kafka数据的时候, 或者是output到Clickhouse的时候, CPU会下降, 在做filter的时候, CPU会上升. 所以有波动, 我觉得正常. 你可以和网络流量做下对比, 应该是互补的关系.

CPU占用高, 我觉得Grok占大部分. 建议把 `(.*)` 改成 `[^,]+?`  直接写 .* , 我按以往经验觉得, 对有些匹配不到的message, 可能会导致CPU大幅上涨.

**Comment by tianjinsong** [comment]
多谢！
