### ISSUE TITLE
hangout hanging

### ISSUE THREAD

**Issue by linshaoyong** [childe/hangout#137]
写入es时如果出现如下错误，hangout就一直挂着没反应，es本身是正常的。
hangout版本0.4.0，es版本5.3.0。

2018-12-06 08:01:00,328 [elasticsearch[_client_][listener][T#4]] ERROR com.ctrip.ops.sysdev.outputs.Elasticsearch - bulk has failed item which NEED to retry
2018-12-06 08:01:00,329 [elasticsearch[_client_][listener][T#4]] ERROR com.ctrip.ops.sysdev.outputs.Elasticsearch - RemoteTransportException[[hostname][ip:port][indices:data/write/bulk[s][p]]]; nested: ProcessClusterEventTimeoutException[failed to process cluster event (put-mapping) within 30s];

相关配置
outputs:
   - Elasticsearch:
        cluster: clustername
        hosts:
            - 10.101.1.1:9300
            - 10.101.1.2:9300
            - 10.101.1.3:9300
        index: 'index-%{+YYYY.MM.dd}'
        index_type: logs
        bulk_actions: 30000
        bulk_size: 30
        flush_interval: 30
        concurrent_requests: 0
        sniff: false

**Comment by KrisOtk** [comment]
他的重试机制用了复用了bulkprocessor,bulkProcessor里面用到了锁,导致死锁;
> bulkprocessor.add->bulkprocessor申请锁->lock->出现调用失败->进入自定义的callback->bulkprocessor.add->再次申请锁,永远在等待
(正常调用成功后,调用callback完成后有个fianlly,里面会释放掉锁)

**Comment by childe** [comment]
@KrisOtk 谢谢回复, 我一直没注意有这个 Issue. 但我不觉得是这个原因造成的.
@linshaoyong 抱歉一直没注意到, 我其实很久很久没维护这个 Java 项目了,   我们后面使用 https://github.com/childe/gohangout/ 这个了.

@KrisOtk 我说可能不是这个原因造成的, 原因
1. 我们之前一直使用(现在也有小量在用), 而且一直会有这种重试出现 , 并没有死锁.
2. 看BulkProcessor 代码, https://github.com/elastic/elasticsearch/blob/master/server/src/main/java/org/elasticsearch/action/bulk/BulkProcessor.java, 其实并不会死锁. 重试的时候已经释放了 Lock

![image](https://user-images.githubusercontent.com/2444825/63570225-feb88e00-c5ae-11e9-938d-20fc9584c67b.png)

**Comment by KrisOtk** [comment]
@childe 抱歉,周末没有登录github,刚刚才看到.
这个我们在生产环境已经遇到过多次才最终确定的问题,可以看下下图中的方法;
![image](https://user-images.githubusercontent.com/24287963/63664064-9c060300-c7f7-11e9-8c8d-7f0b85db86e4.png)
> 所以插件中默认的回调方法,一旦出现失败的情况需要重试时,就非常容易陷入死锁,导致程序hanging.复现的话本地改下回调,对每个item都重新调用bulkprocessor.add(),立马形成死锁
> for example: stdin->elasticsearch 
![image](https://user-images.githubusercontent.com/24287963/63664159-fef79a00-c7f7-11e9-8f49-660a3ff823d3.png)

**Comment by childe** [comment]
@KrisOtk 明白了. 原来是 Execute 里面的锁, 我前面以为是说 Add 里面的. 那的确是可能死锁.

**Comment by KrisOtk** [comment]
> @KrisOtk 明白了. 原来是 Execute 里面的锁, 我前面以为是说 Add 里面的. 那的确是可能死锁.

我目前是加了一个全局的bulkprocessor专门用来重试,重试失败的话直接打日志不进行消费了,这种只适应单个的es集群输出,当然丢mq再消费可能更好一点.

**Comment by KrisOtk** [comment]
> @KrisOtk 明白了. 原来是 Execute 里面的锁, 我前面以为是说 Add 里面的. 那的确是可能死锁.
> 我现在 Go 版本的程序里面, 是每次失败的一批数据独立的 Execute. 因为没有用 BulkProcessor 这种东西, 反而更好处理.

不是太熟悉go,之前的java代码太乱了,自己整理了一波放到线上去消费,比logstash消费方便很多,自由度也高很多,出现问题也有排查的方法.非常感谢!

**Comment by childe** [comment]
@KrisOtk 多谢你, 有空了我去重新写一下.
