### ISSUE TITLE
kafka中消息为序列化后的字节数据，Input反序列化后，filter是否支持消息的过滤和提取

### ISSUE THREAD

**Issue by renrr** [childe/hangout#139]
kafka中消息为序列化后的字节数据，Input反序列化后，filter是否对字节数组支持消息的过滤和提取呢？

**Comment by childe** [comment]
一般来说, Input 反序列化后, 就没有"字节数组"了吧. 还是我理解错了?

**Comment by renrr** [comment]
您好，可能我描述的不太清楚
![image](https://user-images.githubusercontent.com/24388712/56895148-ba165d80-6aba-11e9-97e0-2f5514994809.png)
这个是我的input配置，Input中配置的kafka的反序列化，但是在hangout的控制台是无法输入消息（kafka-console-consumer中是能查到消息），是我配置的有问题吗？

**Comment by childe** [comment]
value.deserializer: org.apache.kafka.common.serialization.ByteArrayDeserializer 使用这个类是有特别的用意吗?

代码里面写的, 只能反序列为字符串, 你用这个类解析的话, 会失败, 不消费数据.
一般是使用下面这个
value.deserializer: org.apache.kafka.common.serialization.StringDeserializer

**Comment by childe** [comment]
另外, 想推一下 https://github.com/childe/gohangout 
当前这个java的几乎不再维护了.

**Comment by renrr** [comment]
好的，StringDeserializer是正常的，想支持ByteArrayDeserializer扩展容易吗？

**Comment by childe** [comment]
https://github.com/childe/hangout/blob/master/hangout-input-plugins/hangout-input-plugins-newkafka/src/main/java/com/ctrip/ops/sysdev/inputs/NewKafka.java#L132
上面这里限制了只取反序列为字符串.

https://github.com/childe/hangout/blob/master/hangout-core/src/main/java/com/ctrip/ops/sysdev/baseplugin/BaseInput.java#L61
上面这里写死了参数的类型是字符串. 

所以要扩容, 好像也不太方便... 如果你有特殊的需求, 需要改这里的代码.

**Comment by renrr** [comment]
好的，谢谢，我试着修改下
