### ISSUE TITLE
保存到文件如何切分日志

### ISSUE THREAD

**Issue by liaoaoyang** [childe/hangout#14]
如果在写入ES的同时希望落地到文件，同时需要切分文件的话，是否是输出到stdout并通过cronolog等方式切分文件？

输出插件并没有看到file类型的插件。

感谢！

**Comment by childe** [comment]
还木有 :(
现在这样, 好像也就是通过Stdout再加第三方工具(linux一般都系统自带logratote吧)切分.

**Comment by liaoaoyang** [comment]
@childe 有没有计划添加支持呢？

使用logrotate也是可以的，但是个人偏好cronolog。

**Comment by childe** [comment]
那个, 我试着写一下吧, 我java也是初学者,写起来各种抄代码, 还可能给你个坑 :)
最近也是有些忙, 还不知道啥时候能写出来..

**Comment by childe** [comment]
我不想写了 内疚到哭... 唉, 哭归哭, 还是先关了吧..
