### ISSUE TITLE
建议添加split 拆分事件filter

### ISSUE THREAD

**Issue by TerrellXu** [childe/hangout#160]
logstash里面split 插件可以把一行数据，拆分成多个事件。
在日志压缩的场景下需要依赖这个插件完成日志拆分操作，建议添加该filter～
下图为拆分事件效果

![image](https://user-images.githubusercontent.com/16453240/86749538-ea1ea080-c06f-11ea-83fe-be7cd3ea091f.png)

**Comment by mad1230** [comment]
这边有例子，可以split
- Add:
   fields:
     target: '<#assign a=url?split("/")>${a[4]}'
   if:
     - '<#if url??>true</#if>'
也可以使用grok
     - Grok:
        match:
          - '%{DATA:log_time}\|%{DATA:thread_name}\|%{DATA:tid}\|%{DATA:level}\|%{DATA:log_class}\|%{DATA:version}\|%{DATA:trace_id}\|%{DATA:trace_uid}\|%{DATA:trace_group}\|%{GREEDYDATA:content}'

**Comment by TerrellXu** [comment]
> 这边有例子，可以split
> 
> * Add:
>   fields:
>   target: '<#assign a=url?split("/")>${a[4]}'
>   if:
>   
>   * '<#if url??>true</#if>'
>     也可以使用grok
>   * Grok:
>     match:
>     
>     * '%{DATA:log_time}|%{DATA:thread_name}|%{DATA:tid}|%{DATA:level}|%{DATA:log_class}|%{DATA:version}|%{DATA:trace_id}|%{DATA:trace_uid}|%{DATA:trace_group}|%{GREEDYDATA:content}'

你说的这个是拆分字段吧，我说的这个需求是拆分事件，1条日志 -> 多条日志

**Comment by childe** [comment]
https://github.com/childe/gohangout/issues/96
