### ISSUE TITLE
output to  Elasticsearch show me error!

### ISSUE THREAD

**Issue by ximply** [childe/hangout#19]
Error message as follows:
ERROR com.ctrip.ops.sysdev.outputs.Elasticsearch$1 elasticsearch[Ransak the Reject][bulk_processor][T#1] bulk got exception
ERROR com.ctrip.ops.sysdev.outputs.Elasticsearch$1 elasticsearch[Ransak the Reject][bulk_processor][T#1] None of the configured nodes are available: [{#transport#-1}{192.168.10.2}{192.168.10.2:8888}]

what's the error mean ?

Here are my output config:
outputs:
    - Elasticsearch:
        cluster: log
        hosts:
            - 192.168.10.2:8888
        index: 'test-%{+YYYY.MM.dd}'
        sniff: false

**Comment by childe** [comment]
8888 should be the transport port, NOT http port, and the real cluster name must be "log"

**Comment by ximply** [comment]
well, my transport port is 9300 and cluster name is log,  but I change 8888 to 9300 it is still this error.

**Comment by ximply** [comment]
Here are nodes infomations:
{
    "_nodes": {
        "total": 1,
        "successful": 1,
        "failed": 0
    },
    "cluster_name": "log",
    "nodes": {
        "uSLTdEOaTqiECq9uX4GA_g": {
            "name": "log-1",
            "transport_address": "192.168.10.2:9300",
            "host": "192.168.10.2",
            "ip": "192.168.10.2",
            "version": "5.0.0-alpha4",
            "build_hash": "3f5b994",
            "total_indexing_buffer": 1702284492,
            "http_address": "192.168.10.2:8888",
            "roles": [
                "master",
                "data",
                "ingest"
            ],
            "settings": {
                "cluster": {
                    "name": "log"
                },
                "node": {
                    "max_local_storage_nodes": "1",
                    "name": "log-1"
                },
                "path": {
                    "data": "/data/log/data",
                    "logs": "/data/log/log",
                    "home": "/usr/local/elasticsearch"
                },
                "discovery": {
                    "zen": {
                        "minimum_master_nodes": "1"
                    }
                },
                "thread_pool": {
                    "bulk": {
                        "queue_size": "1000"
                    },
                    "index": {
                        "queue_size": "480"
                    }
                },
                "client": {
                    "type": "node"
                },
                "http": {
                    "port": "8888"
                },
                "network": {
                    "host": "0.0.0.0"
                }
            },
            "os": {
                "refresh_interval_in_millis": 1000,
                "name": "Linux",
                "arch": "amd64",
                "version": "2.6.32-431.el6.x86_64",
                "available_processors": 24,
                "allocated_processors": 24
            },
            "process": {
                "refresh_interval_in_millis": 1000,
                "id": 14520,
                "mlockall": false
            },
            "jvm": {
                "pid": 14520,
                "version": "1.8.0_101",
                "vm_name": "Java HotSpot(TM) 64-Bit Server VM",
                "vm_version": "25.101-b13",
                "vm_vendor": "Oracle Corporation",
                "start_time_in_millis": 1476931290239,
                "mem": {
                    "heap_init_in_bytes": 17179869184,
                    "heap_max_in_bytes": 17022844928,
                    "non_heap_init_in_bytes": 2555904,
                    "non_heap_max_in_bytes": 0,
                    "direct_max_in_bytes": 17022844928
                },
                "gc_collectors": [
                    "ParNew",
                    "ConcurrentMarkSweep"
                ],
                "memory_pools": [
                    "Code Cache",
                    "Metaspace",
                    "Compressed Class Space",
                    "Par Eden Space",
                    "Par Survivor Space",
                    "CMS Old Gen"
                ],
                "using_compressed_ordinary_object_pointers": "true"
            },
            "thread_pool": {
                "force_merge": {
                    "type": "fixed",
                    "min": 1,
                    "max": 1,
                    "queue_size": -1
                },
                "fetch_shard_started": {
                    "type": "scaling",
                    "min": 1,
                    "max": 48,
                    "keep_alive": "5m",
                    "queue_size": -1
                },
                "listener": {
                    "type": "fixed",
                    "min": 10,
                    "max": 10,
                    "queue_size": -1
                },
                "index": {
                    "type": "fixed",
                    "min": 24,
                    "max": 24,
                    "queue_size": 480
                },
                "refresh": {
                    "type": "scaling",
                    "min": 1,
                    "max": 10,
                    "keep_alive": "5m",
                    "queue_size": -1
                },
                "generic": {
                    "type": "scaling",
                    "min": 4,
                    "max": 128,
                    "keep_alive": "30s",
                    "queue_size": -1
                },
                "warmer": {
                    "type": "scaling",
                    "min": 1,
                    "max": 5,
                    "keep_alive": "5m",
                    "queue_size": -1
                },
                "search": {
                    "type": "fixed",
                    "min": 37,
                    "max": 37,
                    "queue_size": 1000
                },
                "flush": {
                    "type": "scaling",
                    "min": 1,
                    "max": 5,
                    "keep_alive": "5m",
                    "queue_size": -1
                },
                "fetch_shard_store": {
                    "type": "scaling",
                    "min": 1,
                    "max": 48,
                    "keep_alive": "5m",
                    "queue_size": -1
                },
                "management": {
                    "type": "scaling",
                    "min": 1,
                    "max": 5,
                    "keep_alive": "5m",
                    "queue_size": -1
                },
                "get": {
                    "type": "fixed",
                    "min": 24,
                    "max": 24,
                    "queue_size": 1000
                },
                "bulk": {
                    "type": "fixed",
                    "min": 24,
                    "max": 24,
                    "queue_size": 1000
                },
                "snapshot": {
                    "type": "scaling",
                    "min": 1,
                    "max": 5,
                    "keep_alive": "5m",
                    "queue_size": -1
                }
            },
            "transport": {
                "bound_address": [
                    "0.0.0.0:9300"
                ],
                "publish_address": "192.168.10.2:9300",
                "profiles": {}
            },
            "http": {
                "bound_address": [
                    "0.0.0.0:8888"
                ],
                "publish_address": "192.168.10.2:8888",
                "max_content_length_in_bytes": 104857600
            },
            "plugins": [
                {
                    "name": "analysis-ik",
                    "version": "5.0.0-alpha4",
                    "description": "IK Analyzer for Elasticsearch",
                    "classname": "org.elasticsearch.plugin.analysis.ik.AnalysisIkPlugin"
                }
            ],
            "modules": [
                {
                    "name": "aggs-matrix-stats",
                    "version": "5.0.0-alpha4",
                    "description": "Adds aggregations whose input are a list of numeric fields and output includes a matrix.",
                    "classname": "org.elasticsearch.search.aggregations.matrix.MatrixAggregationPlugin"
                },
                {
                    "name": "ingest-common",
                    "version": "5.0.0-alpha4",
                    "description": "Module for ingest processors that do not require additional security permissions or have large dependencies and resources",
                    "classname": "org.elasticsearch.ingest.common.IngestCommonPlugin"
                },
                {
                    "name": "lang-expression",
                    "version": "5.0.0-alpha4",
                    "description": "Lucene expressions integration for Elasticsearch",
                    "classname": "org.elasticsearch.script.expression.ExpressionPlugin"
                },
                {
                    "name": "lang-groovy",
                    "version": "5.0.0-alpha4",
                    "description": "Groovy scripting integration for Elasticsearch",
                    "classname": "org.elasticsearch.script.groovy.GroovyPlugin"
                },
                {
                    "name": "lang-mustache",
                    "version": "5.0.0-alpha4",
                    "description": "Mustache scripting integration for Elasticsearch",
                    "classname": "org.elasticsearch.script.mustache.MustachePlugin"
                },
                {
                    "name": "lang-painless",
                    "version": "5.0.0-alpha4",
                    "description": "An easy, safe and fast scripting language for Elasticsearch",
                    "classname": "org.elasticsearch.painless.PainlessPlugin"
                },
                {
                    "name": "percolator",
                    "version": "5.0.0-alpha4",
                    "description": "Percolator module adds capability to index queries and query these queries by specifying documents",
                    "classname": "org.elasticsearch.percolator.PercolatorPlugin"
                },
                {
                    "name": "reindex",
                    "version": "5.0.0-alpha4",
                    "description": "The Reindex module adds APIs to reindex from one index to another or update documents in place.",
                    "classname": "org.elasticsearch.index.reindex.ReindexPlugin"
                }
            ],
            "ingest": {
                "processors": [
                    {
                        "type": "append"
                    },
                    {
                        "type": "convert"
                    },
                    {
                        "type": "date"
                    },
                    {
                        "type": "date_index_name"
                    },
                    {
                        "type": "fail"
                    },
                    {
                        "type": "foreach"
                    },
                    {
                        "type": "grok"
                    },
                    {
                        "type": "gsub"
                    },
                    {
                        "type": "join"
                    },
                    {
                        "type": "lowercase"
                    },
                    {
                        "type": "remove"
                    },
                    {
                        "type": "rename"
                    },
                    {
                        "type": "script"
                    },
                    {
                        "type": "set"
                    },
                    {
                        "type": "sort"
                    },
                    {
                        "type": "split"
                    },
                    {
                        "type": "trim"
                    },
                    {
                        "type": "uppercase"
                    }
                ]
            }
        }
    }
}

**Comment by ximply** [comment]
I found elasticsearch 5.x is not supported, change to 2.3.2 is OK! Do you have a plan to support 5.x?

**Comment by childe** [comment]
yes, we are also migrating from 2.4 to 5.0, and I am trying to make hangout work for it.

**Comment by ximply** [comment]
It sounds great! Thanks very much!

**Comment by childe** [comment]
@ximply 
https://github.com/childe/hangout/releases
