### ISSUE TITLE
About kafka errors in hangout log file.

### ISSUE THREAD

**Issue by ximply** [childe/hangout#20]
Hangout log file sometimes show me the follows errors:
org.apache.kafka.clients.consumer.internals.ConsumerCoordinator$OffsetCommitResponseHandler pool-1-thread-1 Error UNKNOWN_MEMBER_ID occurred while committing offsets for group xxx 
org.apache.kafka.clients.consumer.internals.ConsumerCoordinator pool-1-thread-1 Auto offset commit failed

Why this occur?

**Comment by childe** [comment]
I use 0.9.0.1 kafka client.  match? 
You can replace it in pom.xml and rebuild using "mvn package -DskipTests"
