### ISSUE TITLE
hangout写入时不参照template定义字段类型

### ISSUE THREAD

**Issue by pcleon** [childe/hangout#23]
我在template中定义了如下类型
        "errno": {
          "type": "long"
        }
但是发现hangout写入后没参照template定义，在es中查看时是string类型
而且我只能在hangout的配置文件中注明
- Convert:
        fields:
            errno: 
                to: integer
                remove_if_fail: true
才会生效。
想请教一下是否hangout写入时不会参考template模板的定义而只参考hangout配置文件中的转换配置？

**Comment by childe** [comment]
肯定是参考ES中的template.

你在通过_source拿数据的时候, 看到的还是原始的字符串, 但是在search , aggragation的时候, 都是按long处理的.

你说没有按template定义, 请给出具体的例子.
