### ISSUE TITLE
output到ES时host列表

### ISSUE THREAD

**Issue by william-yang** [childe/hangout#25]
请问output到ES时，host列表要将所有的data node节点都写上吗？是否可以写client node？
如果将所有的data node都写上；那hangout的负载策略是啥？
我用的es 2.2.1版本，hangout 0.1.8.2版本

**Comment by childe** [comment]
取决于sniff是true还是false.
如果是false, 就是定向发往你写的nodes, 如果是true, 会首先获取data nodes, 然后发往data nodes.
不管是哪一种, 收到数据的Nodes都会再根据route策略进行二次分发.

**Comment by william-yang** [comment]
那是建议发往的node为data nodes还是client nodes 或者是master nodes呢？

**Comment by childe** [comment]
既然sniff的结果是发到data nodes, 那我建议就发datanode吧. 如果你有专门的client node, 当然更好
