### ISSUE TITLE
无法写入ES

### ISSUE THREAD

**Issue by binmu123** [childe/hangout#39]
按照样例配置
- Elasticsearch:
        cluster: hangoutcluster
        hosts:
          - ip1
          - ip2
        index: 'hangout-%{+YYYY.MM.dd}'
        index_type: logs # default logs
        #document_id: ${id} # defautt null, generated by es
        bulk_actions: 20000 #default 20000
        bulk_size: 15 # default 15 MB
        flush_interval: 10 # default 10 seconds
        concurrent_requests: 0 
        timezone: "Asia/Shanghai" # defaut UTC 时区. 只用于生成索引名字的字符串格式化
        sniff: false #default true
无法写入es
首先报ERROR StatusLogger No log4j2 configuration file found. Using default configuration: logging only errors to the console.
其次看日志报错为：
2017-01-06 15:12:23,075 ERROR com.ctrip.ops.sysdev.outputs.Elasticsearch$1 Thread-4 bulk got exception
2017-01-06 15:12:23,076 ERROR com.ctrip.ops.sysdev.outputs.Elasticsearch$1 Thread-4 None of the configured nodes are available:
请教如何解决？

**Comment by childe** [comment]
cluster: hangoutcluster 这里要用你真正的clustername.
