### ISSUE TITLE
hangout读取写入线程数

### ISSUE THREAD

**Issue by binmu123** [childe/hangout#43]
想问下hangout整个 filter 和 output 流程，是不是都在 Kafka 的 consumer 线程中完成？如果是的话是不是意味着hangout的读的线程数就决定output的线程数？
配置中
 topic: 
      app: 2  决定几个线程获取该topic的数据
num.consumer.fetchers: "4"     这个配置有什么意义吗？ 获取数据的线程数不是在那个topic已确定了？

谢谢回答

**Comment by xgwu** [comment]
filter和output流程的确是在kafka的consumer实例里完成的， consumer的数量决定了output的线程数。
num.consumer.fetchers是kafka consumer本身的一个配置项，表示一个consumer可以有多少个线程去topic里fetch数据。 对于kafka来说，一个topic只能被同consumer group里的一个consumer消费，但consumer(进程)本身可以有多线程同时fetch数据。

**Comment by binmu123** [comment]
@xgwu  
你的意思其实就是num.consumer.fetchers其实是设置consumer多少线程去fetch数据，
而topic: app: 2  决定几个线程获取该topic的数据的意思实际是多少个consumer，也就是决定了多少个filter和output  你看我理解的对吧？ 谢谢
