### ISSUE TITLE
是否支持一个useragent的识别

### ISSUE THREAD

**Issue by elain** [childe/hangout#5]
你好：
      针对应用日志比如 nginx/apache这样的日志，往往可能使用到useragent的识别。
例如：
ua	  	Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/39.0.2171.95 Safari/537.36

处理后：
tua_category	  	pc
tua_name	  	Firefox
tua_os	  	Windows 8.1
tua_vendor	  	Mozilla
tua_version	  	41.0

类似于这样的，我刚开始使用hangout，感觉不错，正在做一些数据处理，目前我使用下面的项目来做UA识别，效果不错
https://github.com/bungoume/fluent-plugin-ua-parser

UA的数据库可使用的以下项目，更新较及时，也比较全面。
https://github.com/ua-parser/uap-core/blob/master/regexes.yaml

供参考！

**Comment by childe** [comment]
d042359
