### ISSUE TITLE
es宕机重启之后，hangout不再向es写入数据

### ISSUE THREAD

**Issue by lishengjia** [childe/hangout#62]
hi，我这边遇见一个问题，当es master宕机重启之后，发现hangout不再向es中写入数据，不做任何操作了。重启hangout之后，恢复正常。

请问，这个有什么解决办法吗？

**Comment by childe** [comment]
先贴出来看一下你的hangout配置.
怀疑可能是ES client中数据大量堆积导致线程OOM了.

**Comment by lishengjia** [comment]
hangout的配置如下：
inputs:
    - NewKafka:
        topic:
          test-log: 4
        consumer_settings:
          group.id: test-hangout
          client.id: haha
          bootstrap.servers: a.b.c:6667
          key.deserializer: org.apache.kafka.common.serialization.StringDeserializer
          value.deserializer: org.apache.kafka.common.serialization.StringDeserializer
        codec: plain

filters:
    - Json:
        field: message

outputs:
    - Elasticsearch:
        cluster: my-es-cluster
        hosts:
          - 1.1.1.1:9300
        index: 'test-l7-%{+YYYY.MM.dd}'
        index_type: test-l7
        bulk_actions: 10000
        bulk_size: 30
        flush_interval: 10
        concurrent_requests: 1
        timezone: "Asia/Shanghai"

**Comment by childe** [comment]
如果写ES速度跟得上, 我建议把concurrent_requests: 1设置成0, 这个只是可以通过减少Bulk的线程数降低内存的使用.
但这个不敢保证ES client这边在断开连接之后还能继续尝试新的连接. 我是使用的ES封装好的ES client, 它里面有没有重连的机制我也不清楚.
ES client也没有提供isAvailable这样的方法, 所以对这个问题, 暂时我也没有好的解决方法. 尽量保证ES的可靠吧..

**Comment by lishengjia** [comment]
好的，我试试，多谢

**Comment by xiagujinqiao** [comment]
默认重试策略是：
Network errors (inability to connect)
429 (Too many requests) and
503 (Service unavailable) errors

**Comment by childe** [comment]
@xiagujinqiao 这个是指的BULK失败的重试策略.

@lishengjia 悲剧, 我们ES集群出现大规模故障. 也出现了不能继续消费的故障, 我看了一下, 至少有三种情况.
1. bulk请求发送了, 但是索引在恢复节段, 锁了写, ES client一直在等待返回. 这个也许是正常的等待.
2. bulk请求发送后(约早晨8点左右), 导致创建新索引, 在pending task很多的情况下, 创建索引很可能超时. 但我还不清楚为啥ES client就一直阻塞在这里了, 重启后可以解决.
前两个可能和整个网络环境有关系, 比较中间有防火墙的话, 可能会直接中断idle时间过长的连接, 导致es client一直等待下去. (我还不知道有没有hearbeat机制.)
3. ES client使用的netty4出现fatal error, 估计线程也挂掉了. 这个只能重启.
