### ISSUE TITLE
请问json解析失败的数据可以通过stdout打印出来吗

### ISSUE THREAD

**Issue by jwcn** [childe/hangout#70]
数据量略大时候, 看到日志有大量的解析失败报错, 不确定具体失败的数据长啥样
请问这个可以打印出来定位吗
2017-05-03 03:16:53,092 WARN com.ctrip.ops.sysdev.filters.Json pool-3-thread-1 failed to json parse field: message

**Comment by childe** [comment]
这个最后还是写到ES(如果你的output是ES的话), 到ES里面看就可以了.

或者你可以输出到stdout等等
outputs:
    - Stdout:
        if:
            - <#if tags?? && tags?seq_index_of("jsonfail")!=-1>true</#if>

**Comment by jwcn** [comment]
多谢
