### ISSUE TITLE
output模块kafka配置

### ISSUE THREAD

**Issue by RickyHuo** [childe/hangout#74]
Hangout  Version:0.2.1
能否提供一份新版output kafka模块配置模板，README里面的配置模板不可用。感谢

**Comment by gnuhpc** [comment]
请参考如下配置文件示例：
[https://github.com/childe/hangout/blob/master/conf/testkafkainput.yml](url)
[https://github.com/childe/hangout/blob/master/conf/testkafkaoutput.yml](url)

**Comment by RickyHuo** [comment]
@gnuhpc  感谢帮助
