### ISSUE TITLE
es2.0使用kibana3遇到一个问题

### ISSUE THREAD

**Issue by pengqiuyuan** [childe/hangout#8]
elasticsearch 2.2.1
kibana 3 (使用你修改兼容 es2 的 k3)
![image](https://cloud.githubusercontent.com/assets/4953205/14076133/8a1b7c7c-f511-11e5-9290-7e426f983de4.png)
k3 timepicker选择时间 ，如果es里没有对应时间的index ，es会报错IndexNotFoundException[no such index] ，k3的数据也不会refresh了（之前k3页面显示的是从开头到当前），请问有没有办法避免下
![image](https://cloud.githubusercontent.com/assets/4953205/14076176/08e04650-f512-11e5-9a4a-791580b68b9b.png)
![image](https://cloud.githubusercontent.com/assets/4953205/14076177/132bcfee-f512-11e5-9104-0e57e0ef07bb.png)
![image](https://cloud.githubusercontent.com/assets/4953205/14076183/25dbf894-f512-11e5-8bc7-f684720ace82.png)

**Comment by childe** [comment]
哥, 你怎么提到这里来了.
应该是elastic.js里面的一个bug, 我印象中已经修复了. 是用的dev分支不?

**Comment by pengqiuyuan** [comment]
谢谢，childe，是elastic.js的问题，我的还是1.1.1的版本没注意到
