### ISSUE TITLE
es5.0写入异常

### ISSUE THREAD

**Issue by YDHui** [childe/hangout#80]
从kafka消费写到es的时候报错
日志显示：2017-06-28 18:20:06,740 ERROR com.ctrip.ops.sysdev.outputs.Elasticsearch$1 pool-2-thread-3 bulk got exception: None of the configured nodes are available: [{#transport#-1}{3g60MJJNTMq4LiK82taR5w}{10.10.1.14}{10.10.1.14:9291}]
这个节点是数据节点，我的output es 配置
outputs:
    - Elasticsearch:
        cluster: clustername (这里是正确的集群名)
        hosts:
          - 10.10.1.14:9291
        index: 'java-test-%{+YYYY.MM.dd.HH}'
        index_type: logs # default logs
        #document_id: ${id} # defautt null, generated by es
        bulk_actions: 20000 #default 20000
        bulk_size: 15 # default 15 MB
        flush_interval: 1 # default 10 seconds
        concurrent_requests: 0
        timezone: "Asia/Shanghai" # defaut UTC 时区. 只用于生成索引名字的字符串格式化
        sniff: false #default true
我的input kafka配置
inputs:
    - Kafka:
        codec: json
        encoding: UTF8 # defaut UTF8
        topic:
            java_test_topic: 4
        #topic_pattern: #pattern has high priority,if specified, topic will be ignored
        #   test.*: 3
        consumer_settings:
            group.id: hangout-test
            zookeeper.connect: 10.10.1.18:2181,10.10.1.19:2181,10.10.1.20:2181
            fetch.message.max.bytes: "3145728"
            socket.receive.buffer.bytes: "1048576"
            auto.commit.interval.ms: "1000"

**Comment by childe** [comment]
第一要保证版本一样, hangout里面的elasticsearch client是不是5.0?
第二, hosts里面的端口是用的transport, 就是默认9300的那个

**Comment by YDHui** [comment]
@childe 我clone了你的master版本，我看client版本是5.3，请问如何更换client的版本呢

**Comment by childe** [comment]
@YDHui 如果你是clone后自己编译的,  可以用f9e7e28这个commit的hangout-output-plugins/hangout-output-plugins-elasticsearch. 复制到master下面编译. 因为5.0和5.3的代码有一点点不一样, 只改pom.xml里面的ES Client版本还是不行.

**Comment by childe** [comment]
@YDHui  主要就是下面这里不一样, 你也可以直接改代码.

```
-                        logger.info("bulk done with executionId: " + executionId);
-                        List<DocWriteRequest> requests = request.requests();
+                        log.info("bulk done with executionId: " + executionId);
+                        List<ActionRequest<?>> requests = request.requests();
```

**Comment by childe** [comment]
@YDHui https://github.com/childe/hangout-output-es5/releases 我自己编译了一个5.0.0版本的, 你可以下载后替换hangout中原来的libs下面的elasitcsearch.jar包, 然后把vender里面的elasticsearch-5.3.2.jar换成elasticsearch-5.0.0.jar.

**Comment by YDHui** [comment]
感谢@childe,问题已经解决
