### ISSUE TITLE
请问支持elasticsearch 2.4的权限认证吗

### ISSUE THREAD

**Issue by jwcn** [childe/hangout#83]
es 版本 2.4, 权限认证依赖插件 shield
没看到 ouputs 的 Elasticsearch 里有类似 logstash 的 user 和password 选项嘛
有什么解决办法吗, 谢谢

**Comment by gnuhpc** [comment]
我和@childe 可能都没有es2.x版本再继续添加功能的打算了，我是肯定没有了~@jwcn 你可以来一个pr过来哦~
