### ISSUE TITLE
java.lang.IllegalArgumentException（hangout可以将kakfa0.8数据写入的ES5中吗？）

### ISSUE THREAD

**Issue by mrzhangxing** [childe/hangout#85]
您好，ES5与logstash5强制要求kafka0.10，请问此问题hangout可以解决吗？

**Comment by childe** [comment]
我试了一下最新的版本是可以的, 但是需要你把hanogut/libs下面的Kafka的Jar包换成你对应的版本.

**Comment by mrzhangxing** [comment]
您好，我将有的hanogut/libs/kafka_2.11-0.9.0.1.jar删除掉，把kafka/libs/kafka_2.10-0.8.1.1.jar的复制过来，启动的时候报：ERROR com.ctrip.ops.sysdev.core.Main main java.lang.reflect.InvocationTargetException

**Comment by childe** [comment]
还有另外一个kafka client包.

**Comment by mrzhangxing** [comment]
我下载了响应的版本包还是同样报错：
kafka_2.10-0.8.1.1.jar
kafka-clients-0.8.1.1-kafka1.0.0.jar
我甚至将zk相关的jar也统一，也是报错

**Comment by childe** [comment]
我不知道你用的哪个版本, 我这里测试 https://github.com/childe/hangout/releases/tag/0.3.0 + kafka 0.8.2.2是可以的.

具体的版本和报错都贴一下.

**Comment by mrzhangxing** [comment]
hangout版本：hangout-dist-0.3.0-release-bin.zip
kakfa版本:   kafka_2.10-0.8.1.1
直接解压用0.3.0指定配置文件报：
2017-07-24 10:32:41,480 WARN kafka.utils.Logging$class ConsumerFetcherThread-im_es5_localhost-1500863554627-3619924e-0-2 [ConsumerFetcherThread-im_es5_localhost-1500863554627-3619924e-0-2], Error in fetch kafka.consumer.ConsumerFetcherThread$FetchRequest@39148ecb. Possible cause: _java.nio.BufferUnderflowException


将hangout的libs中的[kafka_2.11-0.9.0.1.jar、kafka-clients-0.9.0.1.jar]删除并替换成[kafka_2.10-0.8.1.1.jar、kafka-clients-0.8.1.1-kafka1.0.0.jar]，就报下面这一句：
Hangout  Version:0.3.0  Copyright @Ctrip   Author : childe@github, gnuhpc@github
2017-07-24 10:40:42,977 ERROR com.ctrip.ops.sysdev.core.Main main java.lang.reflect.InvocationTargetException

**Comment by childe** [comment]
@mrzhangxing   嗯, 是我没测试到, 我用0.8.1.1的client也是不行,  我试着把pom.xml里面的依赖改成0.8.1.1重新编译会出错, 如下. 看起来是因为0.8.1.1还依赖另外的库(但我下载失败了), 所以你单纯的考kafka库还是不行.
```
[ERROR] Failed to execute goal on project hangout-input-plugins-kafka: Could not resolve dependencies for project ctrip:hangout-input-plugins-kafka:jar:0.3.0: The following artifacts could not be resolved: com.sun.jdmk:jmxtools:jar:1.2.1, com.sun.jmx:jmxri:jar:1.2.1: Could not transfer artifact com.sun.jdmk:jmxtools:jar:1.2.1 from/to java.net (https://maven-repository.dev.java.net/nonav/repository): Cannot access https://maven-repository.dev.java.net/nonav/repository with type legacy using the available connector factories: BasicRepositoryConnectorFactory: Cannot access https://maven-repository.dev.java.net/nonav/repository with type legacy using the available layout factories: Maven2RepositoryLayoutFactory: Unsupported repository layout legacy -> [Help 1]
```

不过我试了用0.8.2.2的库, 是可以消费0.8.1.1 kafka server中的数据的, 但没有长时间运行测试稳定性. 所以你可以试一下用0.8.2.2的jar包放到hangout里面替换.

**Comment by mrzhangxing** [comment]
恩，目前用0.8.2.2正常运行，谢谢
