### ISSUE TITLE
这种json数据该如何解析呢？jsonfail

### ISSUE THREAD

**Issue by mrzhangxing** [childe/hangout#87]
**源数据：**

"@fields":{"cluster":"qy_api_v2_pool","body_bytes_sent":"8579","http_versioncode":"Android_32"}\n
"@fields":{"cluster":"qy_api_v2_pool","body_bytes_sent":"8579","http_versioncode":"Android_32"}\n
"@fields":{"cluster":"qy_api_v2_pool","body_bytes_sent":"8579","http_versioncode":"Android_32"}

**想要的数据：**
{"cluster":"qy_api_v2_pool","body_bytes_sent":"8579","http_versioncode":"Android_32"}
{"cluster":"qy_api_v2_pool","body_bytes_sent":"8579","http_versioncode":"Android_32"}
{"cluster":"qy_api_v2_pool","body_bytes_sent":"8579","http_versioncode":"Android_32"}

1、就只是要@fields里面的数据
2、并且分成拆分成3条。（kafka部门要求多条数据合并后传送，减少开销，实际将多条合并）

**像这种需求该如何操作呢？求助**

**Comment by RickyHuo** [comment]
@mrzhangxing 这种情况应该得自己写一个插件了。

可以参考我之前为我们这边的业务写的一个插件[ArrayMap](https://github.com/RickyHuo/hangout-filters-arraymap/blob/master/src/main/java/com.bip.hangout.filters/ArrayMap.java)，我们这边是业务部门将多条json格式日志放到列表里面传进kafka，需要我们自己将一条数据解成多条数据。如下：
```
{"group":"logs", "logs":[{"tags":"hello"},{"tags":"world"}]}
```

代码里重写自己的`filterExtraEvents`方法。

@childe 这里有个问题， `filterExtraEvents`会保留原始数据，原始数据我后面主动丢掉了。不知道childe在这里是处于什么考虑的。

**Comment by mrzhangxing** [comment]
@RickyHuo 感谢
由于我不会写java，找java同事协助了下，做了简单的更改，临时先解决了问题；

https://github.com/childe/hangout/blob/master/hangout-input-plugins/hangout-input-plugins-kafka/src/main/java/com/ctrip/ops/sysdev/inputs/Kafka.java
将源函数
        public void run() {
            ConsumerIterator<String, String> it = kafkaStream.iterator();
            while (it.hasNext()) {
                process(it.next().message(), this.filterProcessors, this.outputProcessors);
            }
改为回车切割：
public void run() {
    ConsumerIterator<String, String> it = kafkaStream.iterator();
    while (it.hasNext()) {
        String messages=it.next().message();
        String msgs[] =messages.split("\n");
        for(String msg :msgs){
            process(msg, this.filterProcessors, this.outputProcessors);
        }

    }
}

**Comment by childe** [comment]
@RickyHuo 谢谢你的回答和代码:) 我写这个功能的原始目的是我们这边的一个需求, 需要把access日志流式的做一些统计, 得到每分钟的一些聚合值写入另外一个索引B, 原始的数据也需要写到索引A. 所以我保留了原始数据. 你如果不想保留的话, 可以直接在filter方法里面返回null. (这个功能也是后面添加的, 为了兼容之前框架写的挺难看..)

@mrzhangxing 你这样做也没问题. 也启发我可以对于decode(plain, json等)功能做些调整, 可以整个程序更好看更好扩展.  但是"多条数据合并后传送，减少开销" 这个说法并不是指把多条数据合在一条里面, 而是说放在一个kafka message set里面一起发出去, 而不是一条一条发. 你们这样做会给后续带来不少麻烦, 比如这个issue..

**Comment by mrzhangxing** [comment]
是有不少麻烦，但由于是跨团队的合作，如果全部更改确实不太好调整，感谢两位的参与
