### ISSUE TITLE
hangou针对nginx request,t如何实现?分割成两个独立字段

### ISSUE THREAD

**Issue by Eagle2017** [childe/hangout#89]
nginx request: https://passport.xxxxx.com/abc/xxxx?callback=jQuery16408744782154264645
请问hangout如何实现?分割成两个独立字段呢，logstash 的实现方式如下：
        if [request] {
             ruby {
                init => "@kname = ['url_path','url_args']"
                code => "
                    new_event = LogStash::Event.new(Hash[@kname.zip(event['request'].split('?'))])
                    new_event.remove('@timestamp')
                    event.append(new_event)
                "
            }
        }

**Comment by xiagujinqiao** [comment]
grok匹配，类似 %{URIPATH:url_path}(?:\?(?<uri>[A-Za-z0-9$.+!*|(){},~@#%&/=:;_?\-\[\]]*)|)  这样处理。

**Comment by Eagle2017** [comment]
可以了，谢谢！
