### ISSUE TITLE
请问Elasticsearch插件支持routing吗？

### ISSUE THREAD

**Issue by mrzhangxing** [childe/hangout#90]
PUT my_index/my_type/1?routing=user1&refresh=true 
{
  "title": "This is a document"
}

主要解决上述问题，logstash的routing功能介绍https://www.elastic.co/guide/en/logstash/5.5/plugins-outputs-elasticsearch.html

**Comment by childe** [comment]
在commit 017c046c1 添加了route功能, 你可以自己make打包一下.

**Comment by mrzhangxing** [comment]
非常感激

**Comment by gnuhpc** [comment]
@mrzhangxing 
commit f4a8c9ac3a6f3becea0ceab7278a1535d86d9de5  这个 @childe 笔误了。
