### ISSUE TITLE
fileter里面可以增加mutate（split）功能么？

### ISSUE THREAD

**Issue by githubnovee** [childe/hangout#91]
如：求增加split功能到字段切割
    if [beat][hostname] == "client" {
        mutate {
            split => ["message" ,"|"]
            add_field => ["xxx", "%{message[0]}"]
        }
    }

**Comment by childe** [comment]
参考  https://github.com/childe/hangout/issues/11

**Comment by githubnovee** [comment]
为什么我写的这个转化不了呢？输出没有grok的字段

源日志
{"@timestamp":"2017-09-04T06:43:47.227Z","offset":539799586,"beat":{"hostname":"test01","name":"test01"},
"input_type":"log","source":"\/data1\/log\/20170904_1400.log",
"fields":{"host":"10.10.10.10","id":"555","name":"XXXX","set":"server","cc_module":"log"},
"message":"20170904144342|1219642208|IhjHHDFKNNhhk98jdhKH|86432203436|TFf8767jnghxjdhjk|398|4000|40001|827|1|64|0|110.110.110.110|120.120.120.120|Suucess|A=1|1504507426|6.9.33|3.02.202","type":"log"}

转化规则
filters:
    - Filters:
        if:
            - '<#if fields.set=="server">true</#if>'
        filters:
            - Grok:
                match:
                    - '^%{DATA:dttime}|%{DATA:uin}|%{DATA:openid}|%{DATA:deviceid}|%{DATA:appid}|%{DATA:gameid}|%{DATA:eventtype}|%{DATA:eventid}|%{DATA:timecost}|%{DATA:accounttype}|%{DATA:clienttype}|%{DATA:code}|%{DATA:extend}|%{DATA:svrip}|%{DATA:clientip}|%{DATA:codemsg}'
                remove_fields: ['message']
            - Add:
                fields:
                    logtypye: 'server'
            - Date:
                src: dttime
                formats:
                    - 'UNIX'
                remove_fields: ['dttime']

输出：

{"dttime":"","logtypye":"server","@timestamp":"2017-09-04T06:43:47.227Z","offset":539799586,"beat":{"hostname":"test01","name":"test01"},
"input_type":"log","source":"\/data1\/log\/20170904_1400.log",
"fields":{"host":"10.10.10.10","id":"555","name":"XXXX","set":"server","cc_module":"log"},"type":"log"}

**Comment by childe** [comment]
`^%{DATA:dttime}\|%{DATA:uin}\|`  | 这个字符要转义

**Comment by githubnovee** [comment]
在使用date的时候怎么转不了unix timestamp

比如我输入时间是 dttime='2017-09-07 20:00:01'
            - Date:
                src: dttime
                formats:
                    - 'UNIX'
                remove_fields: ['dttime']

**Comment by childe** [comment]
和logstash用的同一个库, 参考 https://www.elastic.co/guide/en/logstash/current/plugins-filters-date.html

这种请再开一个新issue
