### ISSUE TITLE
input能支持file tail吗

### ISSUE THREAD

**Issue by modeyang** [childe/hangout#94]
如题

**Comment by childe** [comment]
科比你好哈哈.  目前没有想做, 因为我们这边也没这样的需求, 就没这个动力..
用一个stdin的input 然后 `tail -F test.log | hangout ` :)

**Comment by modeyang** [comment]
别总是科比说咯， 怪不好意思的，哈哈， 主要是对java不太熟，不然我就加一个了。

**Comment by childe** [comment]
看了下logstash-forwarder(filebeat)前身, 发现自己没有能力写一个java版本的file input. 需要考虑的点很多:
- 根据文件模式发现文件
- 过期自动关闭
- 判断文件的truncate/delete等
- 等等...
