### ISSUE TITLE
ES如果没有启动的情况下，数据无法进行重发

### ISSUE THREAD

**Issue by charmfocus** [childe/hangout#95]
当ES服务器未启动时，hangout报错信息为

```
2017-08-23 09:17:21,369 ERROR com.ctrip.ops.sysdev.outputs.Elasticsearch$1 elasticsearch[_client_][bulk_processor][T#1] bulk got exception: None of the configured nodes are available: [{#transport#-1}{iZGs2uoxRvqNT0FKutbY6w}{es}{172.18.0.4:9300}]
```
看源码，应该是下面的代码出现的错误：
`hangout/hangout-output-plugins/hangout-output-plugins-elasticsearch/src/main/java/com/ctrip/ops/sysdev/outputs/Elasticsearch.java`
```java
                    @Override
                    public void afterBulk(long executionId, BulkRequest request, Throwable failure) {
                        log.error("bulk got exception: " + failure.getMessage());
                    }
```
这样的话，怎么进行重试机制呢？

**Comment by charmfocus** [comment]
因为如果ES宕机的情况下，hangout会把队列的数据都消费掉，从而造成数据因ES宕机而丢失。

**Comment by childe** [comment]
最简单的办法是判断failure是不是NoNodeAvailableException, 如果是的话, 就把request里面的所有请求再次塞回去.
但是这样会导致add方法的函数栈不断增加. 当然了加一个sleep会好一些, 如果每次失败sleep(action_number ms), bulk10000条数据失败后就会sleep 10秒, 一小时之后栈也只深360层.

不过终究也不是好办法, 我尝试自已用https://www.elastic.co/guide/en/elasticsearch/client/java-api/current/java-docs-bulk.html这里的方法写了一个Plugin, 上传了一个新的分支 LElasticsearch, 意思是LowLevelElasticsearch.  一方面希望能解决你的问题, 另外也希望能解决bulk子线程OOM后不工作进程也不退出的问题.

我自己这边还没大规模测试, 我明天会上量测一下.

**Comment by modeyang** [comment]
能不能在input中设置一个最大消息队列数，如果超过这个阈值还没有被消费完，hangout自停止或者别的处理方式？

**Comment by childe** [comment]
@modeyang input里面并没有Queue, 上游来一条消息就往后面扔一条. 上面的代码我这边已经在几个topic上面跑了几天了, 看起来是可以的.

**Comment by childe** [comment]
f7aa6b6c8d34dbc70465c4f3d8ec7835bfba7372 添加了集群连不上重试, sleep 60秒之后再重试.
