### ISSUE TITLE
hangout假死，不消费数据

### ISSUE THREAD

**Issue by It-bin** [childe/hangout#97]
使用hangout作为入库工具，长时间跑的过程中发现，hangout的进程在，但却不消费kafka中的数据，查看kafka的group，发现consumer-id不存在。

**Comment by childe** [comment]
我们这边也遇到这种情况, 是因为有子线程out of memory. 特别是ES集群不稳定的时候, ES client这里更容易OOM.
可以确认查询一下日志, 是不是也是因为这个?
你们的heap分配了多少?  我们分配2G, 绝大多数都可以正常工作.

**Comment by It-bin** [comment]
我heap分配了4个G 但是由于系统资源紧张实际上hangout只能有2.5个G的内存可用。。是因为压力大的情况下，导致它的子线程OOM了吗？

**Comment by childe** [comment]
不太明白`heap分配了4个G 但是由于系统资源紧张实际上hangout只能有2.5个G的内存可用`. 如果操作系统只有2.5G内存可用, 那就分2G好了.
我这里遇到的问题几乎全部都是内存引起的, 我们全是跑在docker里面的, 70%的情况是heap不够了, OOM. 还有30%是因为native memory不够了, 因为配置了sappiness=0, 被docker杀掉.
所以我怀疑你可能也是内存不够引起的.

你可以把hangout配置贴出来看一下.

**Comment by It-bin** [comment]
hangout 启动配置：
HO_HEAP_SIZE="${HO_HEAP_SIZE:=4g}"
export HO_LOG_LEVEL="${HO_LOG_LEVEL:=info}"
unset CDPATH
export basedir=$(cd `dirname $0`/..; pwd)

JAVA_OPTS="$JAVA_OPTS -Xmx${HO_HEAP_SIZE}"
JAVA_OPTS="$JAVA_OPTS -Xms${HO_HEAP_SIZE}"
exec java $JAVA_OPTS -cp $basedir/conf/*:$basedir/libs/*:$basedir/modules/* com.ctrip.ops.sysdev.core.Main "$@"

hangout的配置：
inputs:
    - NewKafka:
        topic: 
            sec_dev_log-ceshi-ceshi-1.0_parse: 1
        codec: json
        consumer_settings:
            bootstrap.servers: 10.65.133.25:9092
            value.deserializer: org.apache.kafka.common.serialization.StringDeserializer
            key.deserializer: org.apache.kafka.common.serialization.StringDeserializer
            group.id: ns_es      
outputs:
    #- Stdout: {}
    - Elasticsearch:
        cluster: nsfocus-espc
        hosts:
          - 10.65.133.25
        index: '%{table}-%{ns_date}'
        index_type: ${table} # default logs
        #document_id: ${id} # default null, generated by es
        bulk_actions: 2000 #default 20000
        bulk_size: 10 # default 15 MB
        flush_interval: 5 # default 10 seconds
        concurrent_requests: 8 # default 0, concurrent_requests设置成大于0的数, 意思着多线程处理, 以我应用的经验,还有是一定OOM风险的,强烈建议设置为0
        #timezone: "Asia/Shanghai" # defaut UTC 时区. 只用于生成索引名字的字符串格式化
        sniff: true #default true

----------------------------------------
是这样的，我们的系统资源进程之间抢占有点严重，初始的时候给hangout分配了4G，但随着系统的压力增大，各个进程持续吃内存，导致最后内存被占用光了。此时hangout所占用的内存2.5G。

**Comment by childe** [comment]
flush_interval: 5  #这个我建议设置的多一些, 比如说30
concurrent_requests: 8 #这个强烈建议设置成0

其他看起来没有什么问题, 另外你们的kafka版本是不是 0.9.0.0, 这个版本有个很严重的BUG https://issues.apache.org/jira/browse/KAFKA-2978 导致数据会停止消费

**Comment by It-bin** [comment]
嗯，kafka版本的问题应该排除了。我们的kafka版本是0.10.2.1。 我先按照你说的配置试下，另外我打算将hangout的内存下调为2G ,这样的情况下跑一段时间，看看还是否会出现今天的情况。hangout 内部的线程OOM挂了，hangout感知不到吗？如果可以感知到，那我觉得要不然进程将子线程从新创建或者hangout自身死亡，不然这种进程假死的情况还是不容易发现的。

**Comment by RickyHuo** [comment]
这个问题我也遇到了
input NewKafka，稳定运行几个月都没出问题，近期才出现问题，排查了一段时间没有找到原因。
后来使用input NewKafka， 问题暂时没有复现。

**Comment by childe** [comment]
@It-bin 不谦虚的说, 我对JAVA也是新手.. 我google了, 但没找到怎么捕获子线程里面的异常. 如果你了解, 或者有朋友了解, 可以告诉我, 红包已经准备好了.

**Comment by It-bin** [comment]
我们只探讨问题，讨论技术，我在想能不能利用volatile类型的静态变量做标记变量，在子线程内部做try，然后修改这个标记变量。主线程或者其他的维护线程去间歇性的去轮询这个变量，根据标记做处理？或者我google了一篇博文，http://blog.csdn.net/u013177446/article/details/53995040是不是可以借鉴下？其实作为hangout的作者，还是很厉害的，我的前辈级。这是我的一点想法。仅供参考，抛砖引玉。

**Comment by childe** [comment]
谢谢, 前面我没说清楚, 这个子线程不是我开的, 是ES client的代码开的, 所以我做不到给线程加一个UncaughtExceptionHandler.

**Comment by It-bin** [comment]
恩。原来是这样，好吧。哎，昨天晚上调小内存之后，持续跑大概6-7个小时之后，于凌晨2点左右，该问题又复现。

**Comment by childe** [comment]
按我的经验, 2G Heap 一个线程消费数据, 每批bulk只有最多15M, 如果ES集群稳定, 应该没问题.

还是看下日志, 先确认是什么报错, 是在哪里出问题的. 

我又想到另外一点, 如果你们系统总的内存吃紧, Java(按我的经常特别是netty)其实会用到挺多Heap外内存的, 经常几百M, 也有可能会上G.netty的线程也可能会挂掉 (也有可能会被oom killer干掉, 整个进程挂, 不是你们这种) , 我们这边因为是在docker里面跑的, 内存限死, 也碰到过这个问题. 这个时候日志里面会有netty4.maydie类似的报错.

**Comment by It-bin** [comment]
hi，childe，不知道为什么我启动起来的hangout，老是找不到log4j2的配置文件，无法观察到日志情况。
以下是我的进程的目录结构，con下存放的是yml文件和log4j2的配置文件。
-Xmx4g -Xms4g -cp /opt/nsfocus/espc/deps/hangout/conf/*:/opt/nsfocus/espc/deps/hangout/libs/*:/opt/nsfocus/espc/deps/hangout/modules/* com.ctrip.ops.sysdev.core.Main -f conf/es.yml

**Comment by It-bin** [comment]
昨天加上日志，在跑的过程中改现象又复现了，我捕捉到日志如下
2017-09-16 13:58:46,326 ERROR org.apache.kafka.clients.consumer.internals.ConsumerCoordinator$OffsetCommitResponseHandler pool-6-thread-1 Error UNKNOWN_MEMBER_ID occurred while committing offsets for group ns_es

2017-09-16 13:58:46,476 WARN org.apache.kafka.clients.consumer.internals.ConsumerCoordinator$AutoCommitTask$1 pool-3-thread-1 Auto offset commit failed: Commit cannot be completed due to group rebalance
-----------------------------------------------
网上查看相关资料，主流的说法是，消费不过来，数据太大。自动commit超时。所以这种情况的发生和咱们开始讨论的方向有所不对？

**Comment by childe** [comment]
首先, 第二个只是个WARN, 是因为consumer在提交commit的时候, group正在rebalance, 这个是不会导致消费停止的, 先不管他.

第一个Error我是第一次见, 找了个官方的文档 **UNKNOWN_MEMBER_ID** 是指 **The coordinator is not aware of this member.** (https://kafka.apache.org/protocol)

还有 https://cwiki.apache.org/confluence/display/KAFKA/A+Guide+To+The+Kafka+Protocol#AGuideToTheKafkaProtocol-GroupMembershipAPI 这里提到的:
Note that when this API is used for a "simple consumer," which is not part of a consumer group, then the generationId must be set to -1 and the memberId must be empty (not null). Additionally, if there is an active consumer group with the same groupId, then the commit will be rejected (typically with an UNKNOWN_MEMBER_ID or ILLEGAL_GENERATION error). 

以及
UnknownMemberIdCode : Returned from group requests (offset commits/fetches, heartbeats, etc) **when the memberId is not in the current generation**.

看一下generationID是什么:
Upon every completion of the join group phase, the coordinator increments a GenerationId for the group. This is returned as a field in the response to each member, and is sent in heartbeats and offset commit requests. 

综合上面的情况, 看起来好像发生了这么回事: 消费进程A的heartbeat没有发出去, 被踢出consumer group. 然后进程B接管了这个partition的消费: B发起join_group请求并生成了一个新的GenerationId(比A大1). A又发送了offset commit请求, 但他的GenerationId已经不合法了, 所以报了UNKNOWN_MEMBER_ID的错. (我也只是根据UNKNOWN_MEMBER_ID猜测大概可能是这样的, 有些细节,比如B join_group的时候A感知不到? 或者其实你只有一个hangout进程, 那就是他被踢出后再commit offset也是这个报错.)

我觉得现在问题的关键是,A为什么heartbeat没有及时发出, 被认为超时踢出来了. 默认超时是10s. 
有人给我说heartbeat是随fetch请求一起发出的, 但我没有在网上见到这方面的说法, 我觉得这样也太容易heartbeat超时了, 毕竟一批数据的处理很可能超过10s. 
如果heartbeat是单独的一个线程控制的, 也有不合理的地方, fetch和heartbeat两个线程都有可能单独挂掉, 这样heartbeat就不能发挥应有的作用.

刚刚看到 0.10.1之后, The new Java Consumer now supports heartbeating from a background thread.

如果你只有这一个hangout在消费, 那可能就是因为某些原因被踢出了, 然后就停止在这里了. 如果有多个hangout, 也是陆续都停了..

我建议把日志级别至少开到debug, 然后看一下日志的具体的情况. **注意磁盘空间, 不要写爆了. **

**Comment by It-bin** [comment]
昨天晚上按照找到的资料，修改了newKafka的源码，对于consumer增加了设置单词poll的最大记录数max.poll.records=5000，以及超时时间session.timeout.ms=60000的设置，持续压压力跑了一晚上，hangout假死情况没有出现，但是我得到一个warn:

2017-09-17 08:56:50,890 WARN org.apache.kafka.clients.consumer.internals.ConsumerCoordinator$4 pool-9-thread-1 Auto-commit of offsets {sec_dev_log-ceshi-ceshi-1.0_parse-0=OffsetAndMetadata{offset=53565310, metadata=''}, sec_dev_log-ceshi-ceshi-1.0_parse-1=OffsetAndMetadata{offset=53565310, metadata=''}, sec_dev_log-ceshi-ceshi-1.0_parse-4=OffsetAndMetadata{offset=53565309, metadata=''}, sec_dev_log-ceshi-ceshi-1.0_parse-5=OffsetAndMetadata{offset=53565310, metadata=''}, sec_dev_log-ceshi-ceshi-1.0_parse-2=OffsetAndMetadata{offset=53565310, metadata=''}, sec_dev_log-ceshi-ceshi-1.0_parse-3=OffsetAndMetadata{offset=53565310, metadata=''}} failed for group ns_es: Commit cannot be completed since the group has already rebalanced and assigned the partitions to another member. This means that the time between subsequent calls to poll() was longer than the configured max.poll.interval.ms, which typically implies that the poll loop is spending too much time message processing. You can address this either by increasing the session timeout or by reducing the maximum size of batches returned in poll() with max.poll.records.

上面的错看起来和你分析的是一致的，看起来这样的修改还是起作用的，我将继续持续观测。
